apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospeto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospeto
  template:
    metadata:
      labels:
        app: hospeto
    spec:
      containers:
      - image: okteto.dev/hospeto:latest
        name: hospeto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a86b3c12-734e-4a38-a387-89bb61ce2e8f"
        - name: Vless_Path
          value: "/jkduij897"
        - name: Vmess_UUID
          value: "a86b3c12-734e-4a38-a387-89bb61ce2e8f"
        - name: Vmess_Path
          value: "/uiytre345"
        - name: Share_Path
          value: "/v2link"
